DELIMITER $$

CREATE PROCEDURE CreateUser(IN EMAIL VARCHAR(100), IN USERNAME VARCHAR(64), IN PASSWORD_HASH VARCHAR(128), IN REFRESH_TOKEN TEXT)
BEGIN
	INSERT INTO 
		TB_USER(EMAIL, USERNAME, PASSWORD_HASH, REFRESH_TOKEN)
	VALUES
		(EMAIL, USERNAME, PASSWORD_HASH, REFRESH_TOKEN);
END $$

DELIMITER ;


