DELIMITER $$

CREATE PROCEDURE CreateComment(IN IN_BODY TEXT, IN IN_AUTHOR_ID INT(11), IN IN_POST_ID INT(11))
BEGIN
	INSERT INTO 
		TB_COMMENT(BODY, AUTHOR_ID, POST_ID)
	VALUES
		(IN_BODY, IN_AUTHOR_ID, IN_POST_ID);
END $$

DELIMITER ;


