DELIMITER $$

CREATE PROCEDURE CreatePost(IN IN_TITLE TEXT, IN IN_BODY TEXT, IN IN_AUTHOR_ID INT(11))
BEGIN
	INSERT INTO 
		TB_POST(TITLE, BODY, AUTHOR_ID)
	VALUES
		(IN_TITLE, IN_BODY, IN_AUTHOR_ID);
END $$

DELIMITER ;


