DELIMITER $$

CREATE PROCEDURE GetLastComment()
BEGIN
    SELECT TB_COMMENT.*, TB_USER.USERNAME
    FROM TB_COMMENT
    INNER JOIN TB_USER ON TB_COMMNENT.AUTHOR_ID=TB_USER.ID
    ORDER BY ID DESC
    LIMIT 1;
END $$

DELIMITER ;
