DELIMITER $$

CREATE PROCEDURE GetDuplicateUser(IN IN_EMAIL VARCHAR(100), IN IN_USERNAME VARCHAR(64))
BEGIN
    SELECT *
    FROM TB_USER
    WHERE EMAIL=IN_EMAIL OR USERNAME=IN_USERNAME;
END $$

DELIMITER ;