DELIMITER $$

CREATE PROCEDURE GetPosts()
BEGIN
    SELECT TB_POST.*, TB_USER.USERNAME
    FROM TB_POST
    INNER JOIN TB_USER ON TB_POST.AUTHOR_ID=TB_USER.ID
    WHERE DELETED IS NULL
    ORDER BY TB_POST.CREATED DESC;
END $$

DELIMITER ;