DELIMITER $$

CREATE PROCEDURE GetCommentOfUser(IN IN_COMMENT_ID INT(11), IN IN_USER_ID INT(11))
BEGIN
    SELECT TB_COMMENT.*, TB_USER.USERNAME
    FROM TB_COMMENT
    INNER JOIN TB_USER ON TB_COMMENT.AUTHOR_ID=TB_USER.ID
    WHERE TB_COMMENT.ID=IN_COMMENT_ID AND TB_COMMENT.AUTHOR_ID=IN_USER_ID;
END $$

DELIMITER ;