DELIMITER $$

CREATE PROCEDURE GetPost(IN IN_ID INT(11))
BEGIN
    SELECT TB_POST.*, TB_USER.USERNAME
    FROM TB_POST
    INNER JOIN TB_USER ON TB_POST.AUTHOR_ID=TB_USER.ID
    WHERE TB_POST.ID=IN_ID;
END $$

DELIMITER ;