DELIMITER $$

CREATE PROCEDURE GetPostOfUser(IN IN_POST_ID INT(11), IN IN_USER_ID INT(11))
BEGIN
    SELECT TB_POST.*, TB_USER.USERNAME
    FROM TB_POST
    INNER JOIN TB_USER ON TB_POST.AUTHOR_ID=TB_USER.ID
    WHERE TB_POST.ID=IN_POST_ID AND TB_POST.AUTHOR_ID=IN_USER_ID;
END $$

DELIMITER ;