DELIMITER $$

CREATE PROCEDURE GetComments(IN IN_POST_ID INT(11))
BEGIN
    SELECT TB_COMMENT.*, TB_USER.USERNAME
    FROM TB_COMMENT
    INNER JOIN TB_USER ON TB_COMMENT.AUTHOR_ID=TB_USER.ID
    WHERE DELETED IS NULL;
END $$

DELIMITER ;