CREATE TABLE `TB_POST_TAG`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `POST_ID` INT NOT NULL,
    `TAG_ID` INT NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`POST_ID`) REFERENCES `TB_POST`(`ID`),
    FOREIGN KEY (`TAG_ID`) REFERENCES `TB_TAG`(`ID`)
)