CREATE TABLE `TB_USER`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `EMAIL` VARCHAR(100) NOT NULL UNIQUE,
    `USERNAME` VARCHAR(64) NOT NULL UNIQUE,
    `PASSWORD_HASH` VARCHAR(128) NOT NULL,
    `REFRESH_TOKEN` LONGTEXT,
    PRIMARY KEY(`ID`)
)