CREATE TABLE `TB_COMMENT`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `BODY` TEXT,
    `CREATED` DATETIME NOT NULL DEFAULT NOW(),
    `DELETED` DATETIME,
    `AUTHOR_ID` INT NOT NULL,
    `POST_ID` INT NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`AUTHOR_ID`) REFERENCES `TB_USER`(`ID`),
    FOREIGN KEY (`POST_ID`) REFERENCES `TB_POST`(`ID`)
)